name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false  # This queues instead of canceling

jobs:
  deploy:
    env:
      PROJECT_NUMBER: "1002264675194"
      SERVICE_ACCOUNT_EMAIL: "payload-cms-sa-github-actions@agency-buyers-platform.iam.gserviceaccount.com"
      PROJECT_ID: "agency-buyers-platform"
      REGION: "australia-southeast1"
      IMAGE_PATH: "australia-southeast1-docker.pkg.dev/agency-buyers-platform/payload-cms-repo/payload-cms"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool-2/providers/github-provider'
          service_account: '${{ env.SERVICE_ACCOUNT_EMAIL }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Create Cloud Build config file'
        run: |
          cat > cloudbuild.yaml << EOF
          steps:
          - name: 'gcr.io/cloud-builders/docker'
            args: ['build', '-t', '${{ env.IMAGE_PATH }}:${{ github.sha }}', '.']
          - name: 'gcr.io/cloud-builders/docker'
            args: ['push', '${{ env.IMAGE_PATH }}:${{ github.sha }}']
          options:
            logging: CLOUD_LOGGING_ONLY
          EOF

      - name: 'Build and push Docker image'
        run: |
          gcloud builds submit --config cloudbuild.yaml

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy payload-cms \
            --image=${{ env.IMAGE_PATH }}:${{ github.sha }} \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated

